/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adr.main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author yaroslav
 */
public class PanelGPI extends javax.swing.JPanel {

    final private AlcorAdrApp theApp;
    final public Timer tRefreshStates;
    final public Timer tRefreshValues;
    final public Timer tPolling;
    
    /**
     * Creates new form PanelGPI
     */
    public PanelGPI( AlcorAdrApp app) {
        initComponents();
        theApp = app;
        tRefreshStates = new Timer( 100, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                btnRefresh.setEnabled(   theApp.GetDevGPI().isInitialized());
                btnConfigure.setEnabled( theApp.GetDevGPI().isInitialized());
                chkLoopCycle.setEnabled( theApp.GetDevGPI().isInitialized());
            }
        });
        
        tRefreshStates.start();
        
        tRefreshValues = new Timer( 100, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if( !edtGPIAddressValue.isEnabled())
                    if( theApp.GetDevGPI().GetAddress() != null)
                        edtGPIAddressValue.setText( "0x00" + theApp.GetDevGPI().GetAddress());
                    else
                        edtGPIAddressValue.setText( "NULL");
                
                String bits = theApp.GetDevGPI().GetBits();
                
                JLabel labels[] = { lblValue_TI_01, lblValue_TI_02, lblValue_TI_03, lblValue_TI_04, lblValue_TI_05,
                                    lblValue_TI_06, lblValue_TI_07, lblValue_TI_08, lblValue_TI_09, lblValue_TI_10,
                                    lblValue_TI_11, lblValue_TI_12 };
                
                if( bits != null && bits.length() == 12) {
                    
                    for( int i=0; i<12; i++) {

                        if(      bits.charAt( i) == '0')
                            labels[i].setIcon( theApp.GetResources().getIconBigRed());
                        else if( bits.charAt( i) == '1')
                            labels[i].setIcon( theApp.GetResources().getIconBigGreen());
                        else
                            labels[i].setIcon( theApp.GetResources().getIconBigBlack());
                    }
                }
                else {
                    for( int i=0; i<12; labels[i++].setIcon( theApp.GetResources().getIconLittleGrey()));
                }
            }
        });
        
        tRefreshValues.start();
        
        tPolling = new Timer( 1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if( theApp.GetConnectionState() == AlcorAdrConstants.CONNECT_CONNECTED)
                    theApp.GetRxTx().AddCommandToQueue( theApp.GetDevGPI().cmdGetValues(), theApp.GetDevGPI());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblGPIAddrTitle = new javax.swing.JLabel();
        edtGPIAddressValue = new javax.swing.JTextField();
        lblCStitle = new javax.swing.JLabel();
        chkCSvalue = new javax.swing.JCheckBox();
        btnConfigure = new javax.swing.JButton();
        lblValue_TI_01 = new javax.swing.JLabel();
        lblTitle_TS_01 = new javax.swing.JLabel();
        lblValue_TI_02 = new javax.swing.JLabel();
        lblTitle_TS_02 = new javax.swing.JLabel();
        lblValue_TI_03 = new javax.swing.JLabel();
        lblTitle_TS_03 = new javax.swing.JLabel();
        lblValue_TI_04 = new javax.swing.JLabel();
        lblTitle_TS_04 = new javax.swing.JLabel();
        lblValue_TI_05 = new javax.swing.JLabel();
        lblTitle_TS_05 = new javax.swing.JLabel();
        lblValue_TI_06 = new javax.swing.JLabel();
        lblTitle_TS_06 = new javax.swing.JLabel();
        lblValue_TI_07 = new javax.swing.JLabel();
        lblTitle_TS_07 = new javax.swing.JLabel();
        lblValue_TI_08 = new javax.swing.JLabel();
        lblTitle_TS_08 = new javax.swing.JLabel();
        lblValue_TI_09 = new javax.swing.JLabel();
        lblTitle_TS_09 = new javax.swing.JLabel();
        lblValue_TI_10 = new javax.swing.JLabel();
        lblTitle_TS_10 = new javax.swing.JLabel();
        lblValue_TI_11 = new javax.swing.JLabel();
        lblTitle_TS_11 = new javax.swing.JLabel();
        lblValue_TI_12 = new javax.swing.JLabel();
        lblTitle_TS_12 = new javax.swing.JLabel();
        chkLoopCycle = new javax.swing.JCheckBox();
        btnRefresh = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 220)));
        setMaximumSize(new java.awt.Dimension(250, 870));
        setMinimumSize(new java.awt.Dimension(250, 870));
        setPreferredSize(new java.awt.Dimension(250, 870));
        setLayout(null);

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("GPI - Цифровые входы");
        add(lblTitle);
        lblTitle.setBounds(0, 0, 250, 20);

        lblGPIAddrTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGPIAddrTitle.setText("Адрес");
        add(lblGPIAddrTitle);
        lblGPIAddrTitle.setBounds(10, 30, 60, 30);

        edtGPIAddressValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtGPIAddressValue.setText("-");
        edtGPIAddressValue.setEnabled(false);
        add(edtGPIAddressValue);
        edtGPIAddressValue.setBounds(70, 30, 80, 30);

        lblCStitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCStitle.setText("CS");
        add(lblCStitle);
        lblCStitle.setBounds(150, 30, 50, 30);

        chkCSvalue.setEnabled(false);
        add(chkCSvalue);
        chkCSvalue.setBounds(200, 30, 30, 30);

        btnConfigure.setText("Настроить");
        btnConfigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigureActionPerformed(evt);
            }
        });
        add(btnConfigure);
        btnConfigure.setBounds(20, 60, 210, 40);

        lblValue_TI_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_01);
        lblValue_TI_01.setBounds(80, 110, 30, 25);

        lblTitle_TS_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_01.setText("TS01");
        add(lblTitle_TS_01);
        lblTitle_TS_01.setBounds(120, 110, 48, 25);

        lblValue_TI_02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_02);
        lblValue_TI_02.setBounds(80, 140, 30, 25);

        lblTitle_TS_02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_02.setText("TS02");
        add(lblTitle_TS_02);
        lblTitle_TS_02.setBounds(120, 140, 47, 25);

        lblValue_TI_03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_03);
        lblValue_TI_03.setBounds(80, 170, 30, 25);

        lblTitle_TS_03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_03.setText("TS03");
        add(lblTitle_TS_03);
        lblTitle_TS_03.setBounds(120, 170, 48, 25);

        lblValue_TI_04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_04);
        lblValue_TI_04.setBounds(80, 200, 30, 25);

        lblTitle_TS_04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_04.setText("TS04");
        add(lblTitle_TS_04);
        lblTitle_TS_04.setBounds(120, 200, 47, 25);

        lblValue_TI_05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_05);
        lblValue_TI_05.setBounds(80, 230, 30, 25);

        lblTitle_TS_05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_05.setText("TS05");
        add(lblTitle_TS_05);
        lblTitle_TS_05.setBounds(120, 230, 48, 25);

        lblValue_TI_06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_06);
        lblValue_TI_06.setBounds(80, 260, 30, 25);

        lblTitle_TS_06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_06.setText("TS06");
        add(lblTitle_TS_06);
        lblTitle_TS_06.setBounds(120, 260, 47, 25);

        lblValue_TI_07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_07);
        lblValue_TI_07.setBounds(80, 290, 30, 25);

        lblTitle_TS_07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_07.setText("TS07");
        add(lblTitle_TS_07);
        lblTitle_TS_07.setBounds(120, 290, 48, 25);

        lblValue_TI_08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_08.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_08);
        lblValue_TI_08.setBounds(80, 320, 30, 25);

        lblTitle_TS_08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_08.setText("TS08");
        add(lblTitle_TS_08);
        lblTitle_TS_08.setBounds(120, 320, 47, 25);

        lblValue_TI_09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_09.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_09);
        lblValue_TI_09.setBounds(80, 350, 30, 25);

        lblTitle_TS_09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_09.setText("TS09");
        add(lblTitle_TS_09);
        lblTitle_TS_09.setBounds(120, 350, 48, 25);

        lblValue_TI_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_10);
        lblValue_TI_10.setBounds(80, 380, 30, 25);

        lblTitle_TS_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_10.setText("TS10");
        add(lblTitle_TS_10);
        lblTitle_TS_10.setBounds(120, 380, 47, 25);

        lblValue_TI_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_11);
        lblValue_TI_11.setBounds(80, 410, 30, 25);

        lblTitle_TS_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_11.setText("TS11");
        add(lblTitle_TS_11);
        lblTitle_TS_11.setBounds(120, 410, 48, 25);

        lblValue_TI_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue_TI_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblValue_TI_12);
        lblValue_TI_12.setBounds(80, 440, 30, 25);

        lblTitle_TS_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_TS_12.setText("TS12");
        add(lblTitle_TS_12);
        lblTitle_TS_12.setBounds(120, 440, 47, 25);

        chkLoopCycle.setText("Опрашивать периодически");
        chkLoopCycle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkLoopCycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLoopCycleActionPerformed(evt);
            }
        });
        add(chkLoopCycle);
        chkLoopCycle.setBounds(20, 790, 210, 30);

        btnRefresh.setText("Обновить");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(20, 820, 210, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigureActionPerformed
        if( edtGPIAddressValue.isEnabled()) {
            //мы отредактировали - надо сохранить и закрыть контролы
            edtGPIAddressValue.setEnabled( false);
            chkCSvalue.setEnabled( false);
        }
        else {
            //мы хотим отредактировать - надо открыть контролы
            edtGPIAddressValue.setEnabled( true);
            chkCSvalue.setEnabled( true);
        }
    }//GEN-LAST:event_btnConfigureActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        theApp.GetRxTx().AddCommandToQueue( theApp.GetDevGPI().cmdGetValues(), theApp.GetDevGPI());
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void chkLoopCycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLoopCycleActionPerformed
        if( chkLoopCycle.isSelected())
            tPolling.start();
        else
            tPolling.stop();
    }//GEN-LAST:event_chkLoopCycleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfigure;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JCheckBox chkCSvalue;
    private javax.swing.JCheckBox chkLoopCycle;
    private javax.swing.JTextField edtGPIAddressValue;
    private javax.swing.JLabel lblCStitle;
    private javax.swing.JLabel lblGPIAddrTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle_TS_01;
    private javax.swing.JLabel lblTitle_TS_02;
    private javax.swing.JLabel lblTitle_TS_03;
    private javax.swing.JLabel lblTitle_TS_04;
    private javax.swing.JLabel lblTitle_TS_05;
    private javax.swing.JLabel lblTitle_TS_06;
    private javax.swing.JLabel lblTitle_TS_07;
    private javax.swing.JLabel lblTitle_TS_08;
    private javax.swing.JLabel lblTitle_TS_09;
    private javax.swing.JLabel lblTitle_TS_10;
    private javax.swing.JLabel lblTitle_TS_11;
    private javax.swing.JLabel lblTitle_TS_12;
    private javax.swing.JLabel lblValue_TI_01;
    private javax.swing.JLabel lblValue_TI_02;
    private javax.swing.JLabel lblValue_TI_03;
    private javax.swing.JLabel lblValue_TI_04;
    private javax.swing.JLabel lblValue_TI_05;
    private javax.swing.JLabel lblValue_TI_06;
    private javax.swing.JLabel lblValue_TI_07;
    private javax.swing.JLabel lblValue_TI_08;
    private javax.swing.JLabel lblValue_TI_09;
    private javax.swing.JLabel lblValue_TI_10;
    private javax.swing.JLabel lblValue_TI_11;
    private javax.swing.JLabel lblValue_TI_12;
    // End of variables declaration//GEN-END:variables
}
